// KIT DATA ARRAY
var namMember = new Array(
"<img src='https://cdn.footballkitarchive.com/2025/09/08/Nj6iH3zB7xwQT82.jpg' class='kit-thumb'> |<b>Atlético Mineiro</b>|<i>adidas</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/06/05/QsmkV4Kz5nWkhCC.jpg' class='kit-thumb'> |<b>Botafogo</b>|<i>Reebok</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/11/24/PHfIEXXh1ienLJs.jpg' class='kit-thumb'> |<b>CR Vasco da Gama</b>|<i>Kappa</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/09/08/w1HCimRzde7jz1T.jpg' class='kit-thumb'> |<b>Ceará</b>|<i>Vozão</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/03/08/9Iyed2Yt2x6kp04.jpg' class='kit-thumb'> |<b>Cruzeiro EC</b>|<i>adidas</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/04/14/Eb23FiUrLFS33cL.jpg' class='kit-thumb'> |<b>EC Bahia</b>|<i>Puma</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/05/24/QMRlP7UQWZkcLND.jpg' class='kit-thumb'> |<b>EC Juventude</b>|<i>19treze</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/08/25/m5zfdMLCIt8b7F3.jpg' class='kit-thumb'> |<b>Flamengo</b>|<i>adidas</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/03/24/318RpnxyuzBf38j.jpg' class='kit-thumb'> |<b>Fluminense</b>|<i>Umbro</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/05/09/y8As1K8qoB1zmtI.jpg' class='kit-thumb'> |<b>Fortaleza EC</b>|<i>Volt Sport</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/10/04/ktJXBSIJrDMJfRR.jpg' class='kit-thumb'> |<b>Grêmio FBPA</b>|<i>Umbro</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/03/26/589wU1TVrqfUVqh.jpg' class='kit-thumb'> |<b>Mirassol FC</b>|<i>Athleta</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/02/17/QaAjSWpu2HhUip0.jpg' class='kit-thumb'> |<b>Palmeiras</b>|<i>Puma</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/02/10/nwixi47dnwCmHL6.jpg' class='kit-thumb'> |<b>Red Bull Bragantino</b>|<i>Puma</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/07/08/DhFCmLpvdClyl3a.jpg' class='kit-thumb'> |<b>SC Corinthians Paulista</b>|<i>Nike</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/09/17/JHItO4TcaGY8GZS.jpg' class='kit-thumb'> |<b>SC Internacional</b>|<i>adidas</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/04/24/3vm6LQZ5dFJEsOQ.jpg' class='kit-thumb'> |<b>Santos FC</b>|<i>Umbro</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/08/19/D7C2n591Q6J8S8d.jpg' class='kit-thumb'> |<b>Sport Recife</b>|<i>Umbro</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/02/05/5yvfkFbpkXSeAbr.jpg' class='kit-thumb'> |<b>São Paulo FC</b>|<i>New Balance</i>|",
"<img src='https://cdn.footballkitarchive.com/2025/11/24/zJTos1inErLmgNc.jpg' class='kit-thumb'> |<b>Vitória</b>|<i>Volt Sport</i>|",  
);
